<?php



	/* check if someone try to access the folder of these files directly */

	if(strpos($_SERVER['REQUEST_URI'], '/pages/')) {

	    header("Location: ../404.php");

	}



	$path = $_SERVER['DOCUMENT_ROOT']."/site/";

	include $path.'amministrazione/services/TodoService.class.php';



	try

	{

	    $TodoService = new TodoService($DB_con);

	    $Todo = $TodoService->getAll();

	}

	catch(PDOException $e)

	{

	     echo $e->getMessage();

	}

?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>TODO List</title>
	<link rel="stylesheet" href="style.css">
</head>
<body>
	<?php 
		// $tasks = listTasks();
		// var_dump($tasks) ?>
	<h1>Todo List</h1>
	<p class="message">
		<?php if ($addtask) {
			echo "task added successfully<br>";
		}
		echo $error;
		?>
	</p>
	<h2><a href="index.php?new=true">Add a Task</a></h2>
	<?php if($new){
		include 'taskform.php';
	} ?>




	<h2>Current Tasks
		<?php

			$tasks = listTasks();
			$nbTasks = count($tasks);
			if ($nbTasks > 0) {
				echo " : ".$nbTasks;
			}
		?>
	</h2>

	<table class="table table-striped table-bordered table-hover" id="dataTables-product">

                            <thead>

                                <tr>

                                    <th width="120px">Nom</th>

                                    <th width="120px">Code</th>

                                    <th>Description</th>

                                    <th width="100px">Modifier</th>

                                    <th width="100px">Supprimer</th>

                                </tr>

                            </thead>

                            <tbody>

                            <?php 

                                foreach ($Todo as $Todos) {
                                    $description = strip_tags(html_entity_decode($todo->getDescription()));
                                    
                                    

                                    echo "<tr data-prod='".$todo->getId()."'>";

                                    echo    "<td class='prod-title'>".$todo->getName()."</td>";

                                    echo    "<td>".$description."</td>";

                                    echo    "<td>".$todo->getdate()."</td>";

                                    echo    "<td class='text-center'>".

                                                "<a href='index.php?page=edit-produit&produit=".$todo->getId()."'><button type='button' class='btn btn-success btn-circle' >".

                                                    "<i class='fa fa-pencil'></i>".

                                                "</button></a>".

                                            "</td>";

                                    echo    "<td class='text-center'>".

                                                "<button type='button' data-id='".$product->getId()."' class='btn-delete btn btn-danger btn-circle' data-toggle='modal' data-target='#confirmationModal'>".

                                                    "<i class='fa fa-trash-o '></i>".

                                                "</button>".

                                            "</td>";

                                    echo "</tr>";

                                };

                            ?>

                            </tbody>

                        </table>
	<p>
		<a id='clear' href="index.php?clear=true">delete all tasks</a> 
		<a id='undo' href="index.php?undo=true">undo last action</a>
	</p>
	<script src='js/app.js'></script>
</body>
</html>